@baseUrl = http://localhost:3000
@contentType = application/json

### 1. Iniciar sesión (Opcional)
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "correo": "admin@bioactiva.com",
  "password": "AdminPassword123!"
}

###

### 2. Consultar SUNAT por RUC válido (Existe en nuestra base simulada)
GET {{baseUrl}}/organizations/sunat/20555444332
Content-Type: {{contentType}}

###

### 3. Consultar SUNAT por Razón Social (Búsqueda parcial de texto)
GET {{baseUrl}}/organizations/sunat/Bioactiva
Content-Type: {{contentType}}

###

### 4. Consultar SUNAT por RUC no registrado (Inexistente en SUNAT)
GET {{baseUrl}}/organizations/sunat/99999999999
Content-Type: {{contentType}}

###

### 5. Crear una Organización
# @name createOrganization
POST {{baseUrl}}/organizations
Content-Type: {{contentType}}

{
  "codigoCliente": "CLI-ORG-500",
  "nombre": "Organizacion General S.A.",
  "nombreComercial": "Organizacion General",
  "tipo": "EMPRESA_NACIONAL",
  "tamano": "GRANDE",
  "ruc": "20555444332",
  "idAuthor": 1
}

###

# Guarda el ID de la organización creada de la respuesta
@orgId = {{createOrganization.response.body.id}}

### 6. Listar Todas las Organizaciones (GET /organizations)
GET {{baseUrl}}/organizations
Content-Type: {{contentType}}

###

### 7. Consultar Detalle de Organización por ID (GET /organizations/:id)
GET {{baseUrl}}/organizations/{{orgId}}
Content-Type: {{contentType}}

###

### 8. Editar Organización por ID (PATCH /organizations/:id)
PATCH {{baseUrl}}/organizations/{{orgId}}
Content-Type: {{contentType}}

{
  "nombreComercial": "Org General Editada",
  "tamano": "PEQUENO",
  "ubicacion": "San Isidro, Lima",
  "sector": "TECNOLOGIA"
}
