sonar.projectKey=BIOACTIVA-Backend
sonar.projectName=BIOACTIVA Backend
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.spec.ts,src/modules/activities/**,src/modules/common/**,src/modules/invitations/**,src/modules/leads/**,src/modules/notifications/**,src/modules/quotations/**,src/modules/reset_password/**
sonar.cpd.exclusions=**/*.dto*.ts,**/mail/templates/**
sonar.sourceEncoding=UTF-8