sonar.projectKey=BIOACTIVA-Backend
sonar.projectName=BIOACTIVA Backend
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.spec.ts
sonar.cpd.exclusions=**/*.dto*.ts,**/mail/templates/**
sonar.sourceEncoding=UTF-8